version: '2'
services:
  db:
    image: mariadb:latest
    volumes:
      - './db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: farm
      MYSQL_DATABASE: farm
      MYSQL_USER: farm
      MYSQL_PASSWORD: farm

  www:
    depends_on:
      - db
    image: farmos/farmos:dev
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -e

        wait_db_ready() {
            while { ! exec 3<>/dev/tcp/db/3306; } > /dev/null 2>&1; do sleep 0.1; done
        }

        if ! [ "$$(ls -A /var/www/html/)" ]; then
          echo "farmOS webroot not detected. Copying from pre-built codebase in the Docker image."
          cp -rp /tmp/www/. /var/www/html
          wait_db_ready
          drush site-install farm --debug --yes --locale=us --db-url=mysql://farm:farm@db/farm --site-name=Test0 --account-name=root --account-pass=test install_configure_form.update_status_module='array(FALSE,FALSE)'
        fi

        wait_db_ready

        find /farmos_dev_modules -maxdepth 1 -mindepth 1 -execdir sh -c '\
            echo Symlinking and drush enabling $$(basename {}) && \
            ln -sTf /farmos_dev_modules/$$(basename {}) /var/www/html/sites/all/modules/$$(basename {}) && \
            drush --root=/var/www/html pm-enable --yes $$(basename {})' \;

        echo "ready" > /var/www/html/www-container-fs-ready

        exec docker-entrypoint.sh apache2-foreground
    volumes:
      - './www:/var/www/html'
      - './php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini'
      - '../farmos_wfs:/farmos_dev_modules/farmos_wfs'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=172.22.0.1
