version: '2'
services:
  www:
    image: farmos/farmos:3.1.1
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -ex

        wait_db_ready() {
            true
        }

        if [ -d /opt/drupal ] && ! [ "$$(ls -A /opt/drupal/)" ]; then
          echo "farmOS codebase not detected. Copying from pre-built files in the Docker image."
          cp -rp /var/farmOS/. /opt/drupal

          mkdir -p /opt/drupal/keys
          chown -R www-data:www-data /opt/drupal/keys

          wait_db_ready
          su www-data -s /bin/bash -c 'drush site-install farm --locale=en --db-url=sqlite://sites/example.com/files/.ht.sqlite --site-name=Test0 --account-name=root --account-pass=test'

          echo "
        \$$settings['file_private_path'] = '/opt/drupal/web/sites/default/private/files';

        " >> /opt/drupal/web/sites/default/settings.php

          mkdir -p /opt/drupal/web/sites/default/private/files
          chown -R www-data:www-data /opt/drupal/web/sites/default/private/files
        fi

        wait_db_ready

        /bin/bash <<'EOF'
            drush --root=/opt/drupal pm-enable --yes farm_material
            drush --root=/opt/drupal pm-enable --yes simple_oauth_password_grant
            drush --root=/opt/drupal pm-enable --yes farm_api_default_consumer

            composer config repositories.farmos_dev_modules '{"type": "path", "url": "/farmos_dev_modules/farmos_wfs"}'

            composer require --with-all-dependencies symbioquine/farmos_wfs @dev

            drush --root=/opt/drupal pm-enable farmos_wfs
        EOF

        exec docker-entrypoint.sh apache2-foreground
    volumes:
      - './www:/opt/drupal'
      - './php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini'
      - '../farmos_wfs:/farmos_dev_modules/farmos_wfs'
      - '../composer.json:/farmos_dev_modules/farmos_wfs/composer.json'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=172.22.0.1
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/www-container-fs-ready
