services:
  db:
    image: postgres:16
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm

  www:
    depends_on:
      - db
    image: farmos/farmos:4.0.0-beta2
    volumes:
      - './www:/opt/drupal'
    ports:
      - '80:80'
    environment:
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/www-container-fs-ready
