version: '3'
services:
  db:
    image: postgres:12
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm

  www:
    depends_on:
      - db
    # TODO: change the image to remove the '-dev' part once there's a prod release of 2.x
    image: farmos/farmos:2.x-dev
    volumes:
      - './www:/opt/drupal'
    ports:
      - '80:80'
    environment:
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/www-container-fs-ready
