name: Test 2.x installation via composer from Drupal.org
on:
  schedule:
    - cron: '0 8 * * *' # Run at 8AM UTC.

jobs:
  two-point-x-composer-install-from-drupal-dot-org:
    name: Test 2.x installation via composer from Drupal.org
    runs-on: ubuntu-20.04
    steps:
      - name: Get a docker-compose.yml file approximating a production site
        run: curl https://raw.githubusercontent.com/symbioquine/farmOS_wfs/2.x/docker/docker-compose.prod-demo.yml -o docker-compose.yml
      - name: Start containers
        run: docker-compose up -d
      - name: Wait until www container is ready
        run: until [ -f ./www/www-container-fs-ready ]; do sleep 0.1; done && while { ! exec 3<>/dev/tcp/localhost/5432; } > /dev/null 2>&1; do sleep 0.1; done
      - name: Do a site-install
        run: docker-compose exec -u www-data -T www bash -c 'drush site-install farm --locale=en --db-url=pgsql://farm:farm@db/farm --site-name=Test0 --account-name=root --account-pass=test'
      - name: Add farmOS_wfs-2.x-dev via composer
        run: docker-compose exec -u www-data -T www composer require drupal/farmos_wfs
      - name: Use drush to enable farmOS_wfs
        run: docker-compose exec -u www-data -T www drush en farmos_wfs
      - name: Perform Minimal Validation of a GetCapabilities Request
        run: |
            set -e
            OAUTH2_ACCESS_TOKEN=`curl -X POST -d "grant_type=password&username=root&password=test&client_id=farm&scope=openid" http://localhost/oauth/token | grep -Po 'access_token":"\K[^"]+'`
            GET_CAPABILITIES_RESPONSE=`curl --header "Authorization: Bearer $OAUTH2_ACCESS_TOKEN" "http://localhost/wfs?SERVICE=WFS&REQUEST=GetCapabilities"`
            echo $GET_CAPABILITIES_RESPONSE | grep -q '<ows:Title>farmOS OGC WFS API</ows:Title>'
